{% set name = "typstyle" %}
{% set version = "0.11.34" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/Enter-tainer/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ce0646d161ee87abbc35ef97e83856310e54a12438a6234b152e281b1cec0af8

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typstyle --version

about:
  home: https://github.com/Enter-tainer/typstyle
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: Beautiful and reliable typst code formatter

extra:
  recipe-maintainers:
    - pavelzw
