{% set name = "typstyle" %}
{% set version = "0.11.35" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/Enter-tainer/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aac4abdd6d7f24321d34b43b8684bc64dba7faad964a2159fcb8842387de0e87

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typstyle --version

about:
  home: https://github.com/Enter-tainer/typstyle
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: Beautiful and reliable typst code formatter

extra:
  recipe-maintainers:
    - pavelzw
