{% set name = "typstyle" %}
{% set version = "0.12.4" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/Enter-tainer/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c25a89e15d3c3b5cd4e1e0a5c416796fc5408f8c47508e36b2c3676486a23d4a

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typstyle --version

about:
  home: https://github.com/Enter-tainer/typstyle
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: Beautiful and reliable typst code formatter

extra:
  recipe-maintainers:
    - pavelzw
