{% set name = "typstyle" %}
{% set version = "0.12.1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/Enter-tainer/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 68138962a660bec25cfa81503753505a02dc6b14f7b1b7b587c8cd521e96f8e0

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - typstyle --version

about:
  home: https://github.com/Enter-tainer/typstyle
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: Beautiful and reliable typst code formatter

extra:
  recipe-maintainers:
    - freundTech
    - pavelzw
