{% set name = "typstyle" %}
{% set version = "0.12.7" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/Enter-tainer/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 53656d85125b9f96f12bd1c98bb9e3f0a58c9047efcfa3d3f216e54665e687cb

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - typstyle --version

about:
  home: https://github.com/Enter-tainer/typstyle
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: Beautiful and reliable typst code formatter

extra:
  recipe-maintainers:
    - pavelzw
